name: ci

on:
  push:
    branches: 
      - main
    tags:
      - "v*.*.*"

jobs:
  deno:
    if: ${{ github.ref == 'refs/heads/main' }}
    uses: okamo1984/workflows/.github/workflows/deno.yml@a05baa16e2f58bdb0714094da754aa191fd3d34e
    with:
      checkfiles: main.ts

  compile:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Deno
        uses: denoland/setup-deno@v1        
      - name: Compile
        run: deno compile -o ug --unstable --allow-read --allow-env --allow-run --allow-write main.ts
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ug
