name: ci

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  # deno:
  #   if: ${{ github.ref == 'refs/heads/main' }}
  #   uses: okamo1984/workflows/.github/workflows/deno.yml@a05baa16e2f58bdb0714094da754aa191fd3d34e
  #   with:
  #     checkfiles: main.ts

  zig:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: master
      - name: Format check
        run: zig fmt --check main.zig

  compile:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # - name: Install Deno
      #   uses: denoland/setup-deno@v1
      # - name: Compile Deno
      #   run: deno compile -o ugd --unstable --allow-read --allow-env --allow-run --allow-write main.ts
      # - uses: actions/setup-go@v3
      #   with:
      #     go-version: 1.19
      # - name: Compile Go
      #   run: go build -o ugg
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: master        
      - name: Compile Zig
        run: zig build-exe --name ugz main.zig
      - name: Compile Zig for MacOS M1
        run: zig build-exe --name ugz-aarch64-macos -target aarch64-macos  main.zig
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ugz
            ugz-aarch64-macos
